{{- $root := . -}}
{{- $fullName := .Release.Name -}}
{{- if .Values.controlPlane.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-control-configmap
  labels:
  {{- include "service.labels" $root | nindent 4 }}
data:
  {{- range $name, $value := .Values.controlPlane.configmap }}
    {{ $name }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
