apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-control-plane
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
