apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress-plane
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  tls:
  - hosts:
    - {{ .Values.ingressPlane.host }}
    secretName: app-wildcard-tls
  rules:
  - host: {{ .Values.ingressPlane.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-ingress-plane
            port:
              number: {{ .Values.ingressPlane.service.port }}
