apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kong-control-plane-to-service
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: app
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - service-app
    ports:
    - protocol: TCP
      port: {{ .Values.controlPlane.service.port }}
