{{- if .Values.postgres.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
{{ end }}
