{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
  - name: postgres
    port: {{ .Values.postgres.service.port }}
  clusterIP: None
{{ end }}
