{{- $root := . -}}
{{- $fullName := .Release.Name -}}
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}-secret
  labels:
  {{- include "service.labels" $root | nindent 4 }}
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
